# Site settings
title: Coding 帮助文档
email: konelove2010@gmail.com
keywords: Coding,git,代码托管,运行空间,在线演示,演示平台,代码质量分析,在线IDE,webide,项目管理,开发协作,悬赏众包,洋葱猴
description: Coding.net 是一个面向开发者的云端开发平台,提供 git代码托管，免费的运行演示空间，代码质量分析，在线Web IDE，项目管理，开发协作，悬赏众包，冒泡社交等功能。 为开发者提供技术讨论和开发，协作工具， Coding 极速的代码体验，让开发更简单。
baseurl: "/help" # the subpath of your site, e.g. /blog/
url: "https://coding.net" # the base hostname & protocol for your site
github_username:  kone
exclude:  ["node_modules","react","test","bower","bower.json","bower","link.js","package.json","README.md","css","static/vendor","static/js","static/css","npm-debug.log"]
destination: _site/help
# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
